src/mod/applications/mod_avmd/mod_avmd.c

- Add media bug before starting avmd thread
- Get FS session via session locate

TELOPS-838: Fixed avmd causing session deadlock

---

src/include/switch_ivr.h
src/mod/applications/mod_dptools/mod_dptools.c
src/mod/applications/mod_http_cache/mod_http_cache.c
src/switch_ivr_play_say.c

- Added error callback for ivr play file
- Support backward compatibility for switch_ivr_play_file method
- Indicate url in mod_http_cache logs

TEL-4484: Added descriptive error for playback and http cache

---

src/switch_core_media.c

Updated on selecting the candidate from FS, this will ignore mdns by default following this proposed draft https://tools.ietf.org/html/draft-mdns-ice-candidates-00 see 3.2. ICE Candidate Processing. On this patch, I won't try to resolve the mdns and just ignored it completely. This is enabled by setting the ignore_ice_mdns channel variable to true

ENGDESK-5454: Add variable to ignore mdns in ice candidates

---

src/mod/loggers/mod_graylog2/mod_graylog2.c

Allow to add static variable in graylog fields. This is useful to add additional information specific to b2bua instance.

TEL-4508: Support static field value in mod_graylog2

---

src/mod/endpoints/mod_sofia/sofia.c

- Add validation in sofia INVITE

ENGDESK-5777: Support rejecting ipv6 in sdp

---

src/include/switch_telnyx.h
src/switch.c
src/switch_telnyx.cpp

- Sync read/write on heartbeat callbacks

TEL-4520: Fix intermittent crash during shutdown

---

src/switch_rtp.c

- Add NULL check to rtcp_recv_msg_p

TEL-4529: Fix crash on read_rtp_packet

---

src/mod/endpoints/mod_sofia/mod_sofia.c
src/mod/endpoints/mod_sofia/prometheus_metrics.cpp
src/mod/endpoints/mod_sofia/prometheus_metrics.h
src/mod/endpoints/mod_sofia/sofia.c

- Improve sofia_connected_calls
- New metric sofia_new_incoming_invite
- New metric sofia_dialplan_rejected_calls

TEL-4539: Added new prometheus alerts

---

src/mod/applications/mod_commands/mod_commands.c

- Add uuid_calls and uuid_channels in show command

TEL-4563: Add lightweight query to get active calls

---

src/mod/applications/mod_commands/mod_commands.c

- Send error message when displace is interrupted by hangup

ENGDESK-7988: Added new error response for uuid_displace

---

src/mod/applications/mod_commands/mod_commands.c
src/mod/applications/mod_dptools/mod_dptools.c
src/switch_ivr_originate.c

Merge the v39.
We've decided to postpone the freeswitch-1.10.15 merge.

NOJIRA: Merge the branched v39

---

src/mod/endpoints/mod_sofia/mod_sofia.h
src/mod/endpoints/mod_sofia/sofia_reg.c

TEL-4736: add gateway register custom variables support

---

src/mod/endpoints/mod_sofia/sofia.c

port of this commit: https://github.com/signalwire/freeswitch/commit/3065cb9168e994b5388c37170c61b0956c91e0d2

TEL-4840: Fix memory leaks caused by improper profile destroy.

---

src/switch_core_media.c
src/switch_rtp.c

This PR second please
This reverts Avaya fix candidate, and adds more crypto debug

Tel 9803 more crypto debug

---

src/mod/endpoints/mod_sofia/sofia.c

Merging Stefan's fix for memory leak @StefanYohansson 
To be merged after v45

TEL-4840: Fix memory leaks caused by improper profile destroy. (#80)

---

src/include/switch_core_media.h
src/include/switch_types.h
src/switch_core_media.c

Fix srtp (crypto) negotiation for Avaya
Revert old fix-candidate (workaround)
Keep debug log changes

ENGDESK-9803 Tel-4928 fix srtp crypto negotiation

---

src/switch_ivr_play_say.c

Voicemail: happy changes to core

---

src/switch_core_media.c
src/switch_rtp.c

Also improves debug logs by using channel name.

Fix checking of rtp_rewrite_timestamps variable

---

src/switch_rtp.c

similar to: https://github.com/team-telnyx/freeswitch/pull/131/files#diff-22fb42adfdcb1b040df31af32a8bf724cda8b03a0b205b75662925482464ac58R1411

TEL-5120: fix zrtp crash in zrtp_send_rtp_callback

---

src/mod/codecs/mod_amrwb/mod_amrwb.c

Example:
To get it configured as:
a=fmtp:102 octet-align=0; mode-set=0,1,2,3; (...)
on an outbound call, configuration must be set to:
<configuration name="amrwb.conf">
<settings>
(...)
<param name="mode-set-overwrite" value="0"/>
<param name="mode-set" value="0,1,2,3"/>
(...)
</settings>
</configuration>
Also fix -Werror=unused-variable for passthrough.

ENGDESK-15706 Make mode-set for AMR-WB configurable

---

src/mod/applications/mod_http_cache/mod_http_cache.c
src/mod/formats/mod_shout/mod_shout.c

- Log local and remote ip/port for http request

TEL-5172: Allow to customize bind ip for mod_http_cache

---

src/switch_rtp.c

When SWITCH_RTP_FLAG_USE_MILLISECONDS_PER_PACKET flag is set
switch_rtp_create is called with ms per packet.
But in a call to switch_core_timer_init this mathod assumed
that it was given microseconds per packet. This assumption
no longer holds once RTP_FLAG_USE_MILLISECONDS_PER_PACKET
was introduced.
This commit makes sure switch_core_timer_init is always called
with ms per packet.

TEL-5188 Fix RTP timer initialization

---

src/include/switch_telnyx.h
src/mod/applications/mod_commands/mod_commands.c
src/switch_rtp.c
src/switch_telnyx.cpp

- Execute callback for packet loss

TEL-5208: Allow to populate custom report in status api

---

src/mod/event_handlers/mod_json_cdr/mod_json_cdr.c

- Allow to backup cdr in case of cdr write failure

TEL-5225: Fix issue where tmp cdr is not deleted

---

src/mod/endpoints/mod_sofia/sofia.c

[json_cdr_normal_call.txt](https://github.com/team-telnyx/freeswitch/files/9527284/json_cdr_normal_call.txt)
[json_cdr_with_ack_timeout.txt](https://github.com/team-telnyx/freeswitch/files/9527285/json_cdr_with_ack_timeout.txt)

ENGDESK-18648: set hangup related variables from leg B to leg A

---

src/include/switch_rtp.h
src/include/switch_types.h
src/mod/applications/mod_commands/mod_commands.c
src/switch_channel.c
src/switch_core.c
src/switch_ivr.c
src/switch_rtp.c

- Add cumulative R and MOS in HANGUP events

TEL-5432 ENGDESK-19498: Add new R and MOS calculation

---

src/mod/asr_tts/mod_unimrcp/mod_unimrcp.c

- Added max_retry attempts when sending mrcp request

TEL-5503: Fix deadlock issue in unimrcp

---

src/switch_core_media.c

- Fixes issue when recovering call with SRTP

TEL-5546: Skip audio validation during call recovery

---

src/switch_rtp.c

Cleanup session check in  ZRTP event callback

TEL-5612: Fix ZRTP Crash

---

src/include/switch_core.h
src/include/switch_ivr.h
src/include/switch_module_interfaces.h
src/mod/applications/mod_dptools/mod_dptools.c
src/mod/asr_tts/mod_unimrcp/mod_unimrcp.c
src/switch_core_asr.c
src/switch_ivr_async.c

- Support new cancel callback in mod_unimrcp
- Add new command try-cancel in detect speech

ENGDESK-22746: Implement cancel in detect speech

---

src/mod/endpoints/mod_sofia/mod_sofia.h
src/mod/endpoints/mod_sofia/sofia.c
src/mod/endpoints/mod_sofia/sofia_glue.c

- Change sip error 608 q.850 mapping to DECLINE

ENGDESK-23329: Add new profile/channel variable to ignore reason header

---

libs/unimrcp/libs/mrcp-client/include/mrcp_application.h
libs/unimrcp/libs/mrcp-client/src/mrcp_application.c
src/mod/asr_tts/mod_unimrcp/mod_unimrcp.c

Crashes details is shared in [TEL-5725](https://telnyx.atlassian.net/browse/TEL-5725) ticket
[TEL-5725]: https://telnyx.atlassian.net/browse/TEL-5725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TEL-5725: Fix for Unimrcp Crashes

---

src/mod/asr_tts/mod_unimrcp/Makefile.am
src/mod/asr_tts/mod_unimrcp/mod_unimrcp.c
src/mod/asr_tts/mod_unimrcp/prometheus_metrics.cpp
src/mod/asr_tts/mod_unimrcp/prometheus_metrics.h

- Adds speech recognition success and failures metrics
- Adds timeouts metrics to mrcp server (lumenvox)

TEL-5764: Add prometheus metrics to mod_unimrcp

---

src/mod/asr_tts/mod_unimrcp/mod_unimrcp.c

This fix is to try to mitigate mod_unimrcp crashes
https://telnyx.slack.com/archives/CK9HD9GNQ/p1699379880843549
https://telnyx.slack.com/archives/CK9HD9GNQ/p1699965024353719

TEL-5825: Fix B2BUA mod_unimrcp crashes

---

src/mod/endpoints/mod_sofia/mod_sofia.c

- Handle already process state for RINGING, PROGRESS and ANSWER when waiting for PRACK

ENGDESK-28798: Fix issue during waiting for PRACK

---

src/mod/endpoints/mod_sofia/sofia_media.c
src/switch_core_media.c

- Add a variable to disable SDP validation during reinvite

TEL-5907: Handle rtp_secure_media with suites during validation

---

src/mod/applications/mod_avmd/Makefile.am
src/mod/applications/mod_avmd/mod_avmd.c
src/mod/applications/mod_avmd/prometheus_metrics.cpp
src/mod/applications/mod_avmd/prometheus_metrics.h

- Added API function to report avmd number of detectors and sessions
- Added prometheus metric for avmd sessions and detectors

TEL-5945: Fix potential deadlock in detectors_thread

---

src/include/switch_core_media.h
src/mod/endpoints/mod_sofia/sofia.c
src/switch_core_media.c
src/switch_rtp.c

- Skip rebuilding local key for missing MKI
- Add skip mki in sofia config

ENGDESK-28183, ENGDESK-28234, ENGDESK-28725: Process crypto key with no MKI index

---

src/mod/applications/mod_avmd/mod_avmd.c

- Add max idle time for avmd detectors
- Fix memory pool leak to global pool

TEL-6033: Fix the avmd global session lock in avmd_session_close

---

src/include/switch_core_media.h
src/include/switch_rtp.h
src/mod/endpoints/mod_sofia/mod_sofia.h
src/mod/endpoints/mod_sofia/sofia.c
src/mod/endpoints/mod_sofia/sofia_glue.c
src/switch_core_media.c
src/switch_rtp.c

- When timeout reach, it will disable rtcp passthru

ENGDESK-29053: Added timeout for rtcp passthru

---

src/mod/endpoints/mod_sofia/sofia.c

- Use Dialog TO User header if Refer-To User is missing
- Use REFER From User header if Dialog TO user is missing

TEL-5950: Handle missing Refer-To User

---

src/mod/endpoints/mod_sofia/sofia.c
src/switch_core_media.c

- Reset  TFLAG_NEW_SDP either in ready or completion state

ENGDESK-33364: Fix issue on handling duplicate or modified SDP.

---

src/include/switch_channel.h
src/mod/endpoints/mod_sofia/mod_sofia.c
src/switch_channel.c

Map the internal freeswitch cause code to sip cause

ENGDESK-33564: Map the internal freeswitch cause code to sip cause

---

src/switch_core_io.c
src/switch_rtp.c

- Fix Fork frame may introduce echo or looping sound.

TEL-6048: Fix issue when fork read frame is not updated

---

src/switch_ivr_bridge.c

- Added new channel var `bridge_warn_continuous_silence`

TEL-6115: Support logging silence/cng frame during bridge

---

configure.ac
src/include/Telnyx/UTL/Thread.h
src/telnyx/utl/Thread.cpp

Reverts team-telnyx/freeswitch#326

Revert "TEL-6122 Get rid of Poco thread pool"

---

src/switch_rtp.c

Reverts team-telnyx/freeswitch#313

Revert "TEL-6127 Do not count in invalid or unsupported XR reports."

---

src/switch_core_codec.c
src/switch_core_io.c
src/switch_core_session.c

Reverts team-telnyx/freeswitch#354

Revert "TEL-6238 Add logs to track the address of codec_read_mutex"

---

src/mod/endpoints/mod_sofia/sofia.c

Reverts team-telnyx/freeswitch#361

Revert "ENGDESK-38038: Remove duplicate identity header added from vanilla FS"
