team-telnyx/freeswitch

- src/mod/applications/mod_conference/conference_member.c
- Conference does not set the session making mod_polly crash
> ENGDESK-4000: Set session member prior to invoking feed_tts

- src/switch_ivr_originate.c
Request to add telnyx_fax variable in the post_originate_event if it's set on the dialplan
> ENGDESK-4225: Add telnyx_fax variable in post_originate_event

- src/switch_core_media.c
Firefox puts fingerprint as global attributes. We have added this global attribute in switch_core_media_validate_common_audio_sdp function (see https://github.com/team-telnyx/freeswitch/commit/66fb2f62e13c8f1721baef56ecf01ae6e90a101e#diff-57a89cb34e86ccb4471a86094b8722dc) but we need to apply this as well on switch_core_media_negotiate_sdp function.
> ENGDESK-4206: Parse fingerprint from global sdp attribute

- src/switch_rtp.c
Right now, once either the port is confirmed or auto adjust
has been performed, auto adjust flag is automatically cleared.
a new channel variable rtp_auto_adjust_always has been introduced
to disable this behavior
> TEL-4343:  Add a new channel variable to always auto adjust RTP

- src/mod/endpoints/mod_sofia/mod_sofia.c
They are cases where sip_cause may contain range value of >900. This error is coming from nua stack and when we retrieve the sip status phrase from this value it returns null. The crash happens when we try to add a suffix tv1 on error phrase. 
The fix is to make sure phrase don't contain null value. The sip_status_phrase will only return null if sip cause is less than 100 or greater than 699. If sip cause is a custom sip error code sip_status_phrase will return empty string otherwise it will return the sip error phrase. If this is a nua error code >900, we consider this as internal server error.
> TELOPS-725: Handle possible nua status code when adding phrase suffix

- src/mod/endpoints/mod_sofia/sofia.c
Adding channel variables for event sofia::notify_refer and rename UniqueID variable to Unique-ID
> ENGDESK-4596: Add channel variables in sofia::notify_refer

- src/mod/applications/mod_dptools/mod_dptools.c
- src/switch_ivr_play_say.c
- Handle possible status code for playing audio file and set that as "current_application_response"
- Add new "Playback-Status-Code" in PLAYBACK_STOP event
> ENGDESK-5043: Add new response for failed audio playback

- libs/esl/fs_cli.c
The generated dialplan for freeswitch is ranging around 3000 - 4000 buffer size. For the purpose of debugging the dialplan command via fs_cli, I have increased the fs_cli command buffer size to 4096.
> TEL-4476: Increase command buffer size for fs_cli

- src/include/switch_scheduler.h
- src/switch_scheduler.c
Add a new method in scheduler to cancel a schedule group based on the description. Most of the sched app commands such as sched_broadcast, sched_hangup, sched_api etc are using the switch_func as the description. By using this new method, we can cancel only a specific sched commands.
> TEL-4487: Add method to cancel group schedule task based on desc

- src/switch_ivr_originate.c
During failover, FS always cleanup the ringback resources including mux_buf:
https://github.com/team-telnyx/freeswitch/blob/telnyx/telephony/master/src/switch_ivr_originate.c#L4017
But FS never reset the mux_buflen which would prevent allocating mux_buf if wrote buffer size is less than mux_buflen in teletone_handler callback:
https://github.com/team-telnyx/freeswitch/blob/telnyx/telephony/master/src/switch_ivr_originate.c#L870
So when it did the memcpy, mux_buf is already been deleted and that would cause the crash on FS.
> TEL-4516: Reset ringback mux buffer length during failover

- src/mod/endpoints/mod_sofia/mod_sofia.c
Add channel variable `override_sip_reason_phrase` to change the error description during hangup
> TEL-4518: Add channel var to override sip reason phrase

- src/include/switch_core_media.h
- src/mod/endpoints/mod_sofia/sofia.c
- src/switch_core_media.c
Added media flag to enable rejecting ipv6 during sdp negotiation
> ENGDESK-5777: Support rejecting ipv6 in sdp

- src/mod/applications/mod_conference/conference_file.c
- src/mod/applications/mod_conference/conference_member.c
- src/mod/applications/mod_conference/mod_conference.c
- src/mod/applications/mod_conference/mod_conference.h
This is to support for publishing speak done events for conference.
Issues in this implementation is we reach the max EFLAGS to support suppressing events for speak done, for now EFLAG_PLAY_FILE_DONE will suppressed both play and speak done events. Alternative to fix this is to disable pedantic or treat include file for mod_conference as isystem which will both suppressed the warning `restricts enumerator values to range of 'int'`. FS are stricts to warning and treat it as errors, disabling this just to support extending enum flags seems not to adhere to FS coding guidelines.
> ENGDESK-5722: Publish speak done events for conference call

- src/include/switch_module_interfaces.h
- src/mod/applications/mod_dptools/mod_dptools.c
- src/mod/applications/mod_http_cache/mod_http_cache.c
- src/switch_ivr_play_say.c
TEL-4599: Add event variable for file interface
- Allow custom file modules to add vars in playback events
- Add custom file module events in channel variable
> TEL-4600: Support retry on http get failure

- libs/sofia-sip/libsofia-sip-ua/nua/nua_client.c
- libs/sofia-sip/libsofia-sip-ua/nua/nua_client.h
- libs/sofia-sip/libsofia-sip-ua/nua/nua_session.c
- Store outgoing prelim request in client session
- Cleanup prelim transaction on client request destroy
> ENGDESK-6986: Fixed FS not sending ACK in reliable provisional response

- src/mod/endpoints/mod_sofia/sofia.c
- src/mod/endpoints/mod_sofia/sofia_glue.c
- src/mod/endpoints/mod_sofia/sofia_reg.c
This is to fix the issue on profile pool getting bigger when webrtc is trying to add/remove gateways dynamically.
> TEL-4696: Gateway to use its own memory pool rather than profile pool

- src/switch_core.c
- src/switch_xml.c
**Issue**:
switch_event_init is caching the output of default ipv4 result from switch_find_local_ip. We can enforce the ip by setting the `force_local_ip_v4` global variable. The problem is somehow the `force_local_ip_v4`  didn't take effect for the switch_event.
**Solution**:
We need to load the global variables before calling switch_event_init. The problem with this change will cause crashes since loading the xml configuration will fire event `RELOADXML` and the switch_event is not yet initialize. To solve this we only need to fire the event by checking the reload flag in switch_xml_open_root. This will not cause an issue because on core init, we are not yet reloading the xml.
> TEL-4781: load global vars before switch_event_init

- debian/control-modules
freeswitch build-deps includes amrnb but miss amrwb
> add libopencore-amrwb-dev as dependency on debian control-modules

- src/switch_core_media.c
Fort incoming SDP response may use cached version.
> ENGDESK-9803 Always check incoming crypto for incoming SDP request

- src/switch_rtp.c
This PR first please
This just hides Homer debug messages behind DEBUG_HOMER macro
> Tel-4894: Hide debug homer behind DEBUG_HOMER define

- src/switch_core_media.c
Use `<action application="set" data="srtp_fix_1=true"/>` or similar to toggle it,
default - not set (not enabled).
> Tel-9803: Hide fix candidate behind srtp_fix_1 flag

- src/switch_ivr_originate.c
**ISSUES**
During 3pcc call when the outbound send a 183 early media, FS will not forward the 183. The reason for this is that FS added a support to offer all codecs during 3pcc call. This changes is causing an audio issue when outbound sends an early media. For now, we disable the early media on this type of call. The problem right now is that when the outbound sends an early media FS don't send any ringing provision response to the inbound.
**SOLUTION**
Instead of disabling the early media, FS will translate 183 early media to a 180 ringing instead.
> TEL-4925: Allow ring ready instead of ignore early media during 3pcc call

- libs/sofia-sip/libsofia-sip-ua/sip/sip_basic.c
- src/mod/endpoints/mod_sofia/sofia_glue.c
**Issue**
STIR/SHAKEN may need to add multiple Identity header. User added this in their dialplan:
```
<action application="export" data="sip_h_identity=..."/>
<action application="export" data="sip_h_identity=... (diversion)"/>
```
The problem is that:
1. Channel Variable is unique
2. Libsofia don't allow multiple Identity headers
**Solution**
I have introduce a special channel variable to add `Identity` Header and support identity diversion.
```
<action application="export" data="sip_identity=..."/>
<action application="export" data="sip_identity_div=... (diversion)"/>
```
libsofia has a support for Identity Header but parsing or creating this header was set to a single entry. I have allowed this header to be added multiple times. Once I applied this changes, I got this outgoing invite …
> TEL-4919: Support Multiple Identity Header 

- src/include/switch_types.h
- src/switch_ivr_async.c
**ISSUE**
ASR events is not published during Transfer. This is due the event is queued in the session and it require to call the switch_core_session_dequeue_event to get the event and publish it. This is done in some of the APP/API command such as bridge, record, sleep etc. This method is not being called when FS transfer the call. To fix this we need to call `fire_asr_events` to publish ASR events immediately but the problem is this will cause to fire 2 events during bridge.
**SOLUTION**
If `fire_asr_events` is set then FS will fire the event immediately and FS will queue the event and later publish it. You need to set `queue_asr_events` to false to prevent FS to queue ASR events. This will prevent 2 events being published in ASR when this two variable is set.
> ENGDESK-8951: Prevent duplicate ASR event when fire_asr_events is set

- src/include/switch_core_media.h
- src/include/switch_rtp.h
- src/include/switch_types.h
- src/switch_core_media.c
- src/switch_rtp.c
This should go on top of merge-ndebug https://github.com/team-telnyx/freeswitch/pull/104
with changes to mod call control: https://github.com/team-telnyx/mod_call_control/pull/14
ENGDESK-11524 Fork (add blocking mode waiting for rx ssrc)
Use wait_ssrc (or ssrc_wait) to tell FS to wait for rx ssrc before firing media_stream::start event.
Example:
uuid_broadcast b34c6ba3-a119-4919-b177-d579f2e58c6e
telnyx_media_stream_start::'{"rx":"udp:35.178.3.213:4901","tx":"udp:35.178.3.213:4900","wait_ssrc":"true"}'
Default behaviour is not to wait for rx ssrc. You will get rx ssrc 0 then in the event.
Note though that interestingly even this mode is still fine for only two streams case:
- if only rx was requested you don't need to know it's ssrc in advance to demultiplex (single stream)
- if only tx …
> Engdesk 11524 fork

- src/include/switch_core_media.h
- src/include/switch_rtp.h
- src/include/switch_types.h
- src/mod/endpoints/mod_sofia/mod_sofia.c
- src/switch_core_media.c
- src/switch_ivr_bridge.c
- src/switch_rtp.c
- src/switch_version.c
This fix can be enabled via RTP bugs, e.g:
`<action application="export" data="rtp_manual_rtp_bugs=SEND_NORMALISED_TIMESTAMPS"/>`
> Engdesk 11745 timestamp fix normalised ts v50

- src/switch_channel.c
- src/switch_rtp.c
Check for flag_mutex in switch_channel_test_flag
and ignore dangling calls to zrtp_event_callback
> TEL-5115 Fix segfault in zrtp

- src/switch_rtp.c
Remote SSRC was checked verbatim but it is stored in network byte order.
Also, add logging around setting of remote SSRC, for debugging.
> TELAPPS-3775 Fix a bug checking remote SSRC in core

- src/switch_rtp.c
RTP payload is signalled on the same byte as Marker bit:
M | x | x | x | x | x | x | x |
Payload types 72-76 are reserved because RTCP packet types 200–204
would otherwise be indistinguishable from RTP payload types 72–76
with the marker bit set (RFC 3550, RFC 3551).
However, when FS receives Receiver Report, PT = 201 (1100 1001b),
it drops M bit and processes packet with PT = 73 (0100 1001b).
This commit prevents assignemnt of remote SSRC in such situation.
> TELAPPS-3775 Fix remote SSRC assignment

- src/switch_rtp.c
Added 5 new variables to variable_media_fork_request of telnyx_media_stream::start event:
- 'transcoding': JSON boolean, tells if forked
stream is being transcoded. This variable will always appear,
the other 4 variables appear only if value of'transcoding' is true
- 'transcoding_codec_in': JSON string, IANA name of codec
used as input RTP to transcoding process (RTP used on call
legs), in lower case
- 'transcoding_codec_out': JSON string, IANA name of codec
used as output RTP from the transcoding process (RTP sent
to addresses requested in fork command ('rx'/'tx'), in lower case
- 'transcoding_pt_in': JSON number, payload number of transcoding input RTP
- 'transcoding_pt_out': JSON number, payload number of transcoding output RTP
Example, when transcoding forked stream:
{
"fork":	{ …
> ENGDESK-16451 Indicate transcoding on telnyx_media_stream_start event

- src/include/switch_rtp.h
- src/switch_core.c
- src/switch_core_media.c
- src/switch_rtp.c
RTP polling timout of 5s exceeded Kamailio's fr_timer
timeout of 3s - this caused SIP to timeout requests
with 408 before RTP could return from a blocking system call.
This commit makes RTP poll timeout configurable via
telnyx_rtp_poll_timeout_s variable, e.g.:
`<action application="set" data="telnyx_rtp_poll_timeout_s=1"/>`
and sets static global default of 5 seconds (TELNYX_RTP_DEFAULT_POLL_TIMEOUT_S)
Additionally
Poll timeout can be configured globally in switch.conf.xml using setting
telnyx-rtp-poll-timeout-s
It is also (still) possible to configure it per channel using variable
telnyx_rtp_poll_timeout_s
> TEL-5189 Set RTP poll timout

- conf/vanilla/autoload_configs/amrwb.conf.xml
- src/mod/codecs/mod_amrwb/mod_amrwb.c
- src/switch_core_media.c
- Add app to print the module config (always print it on module's load)
- Improve codec negotiation according to invite-prefer-oa/invite-prefer-be
- Support new XML config params:
```
default-bitrate
Bitrate mode that will be used if mode-set-overwrite 
and mode-set-overwrite-with-default-bitrate are set).
volte
If set, configures codec for use on cellular networks.
adjust-bitrate
Vary bitrate according to feedback from RTCP.
force-oa
Configure codec in octet aligned mode.
force-be
Configure codec in bandwidth efficient mode.
mode-set-overwrite
When answering a call, use codec bitrate modes from mode-set param, 
instead of mirroring the OFFER.
mode-set-overwrite-with-default-bitrate
If mode-set-overwrite is on, then use default-bitrate mode 
instead of mode-set.
invite-prefer-oa
When …
```
> TEL-5209 TEL-5195 TEL-5190 Changes to AMR-WB

- src/mod/applications/mod_conference/conference_api.c
- src/mod/applications/mod_conference/mod_conference.c
- src/mod/applications/mod_conference/mod_conference.h
A conference with 100 members execute multiple relate api command and causes a deadlock.
Two commands are executed almost at the same time
```
conference 1000 relate 1,...N 2,...N nospeak
conference 1000 relate 2,...N 1,...N nohear
```
The first command will first lock member 1 while it updates the relation from multiple members. This will also perform lock/unlock per each member. This is also applies to the second command in which it will lock member 2 while it updates the relation from multiple members. If this is run almost at the same time there is a chance that the first command is block due to member 2 being lock in the second command. While the second command is block due to member 1 being lock due to the first command. This call sequence will result a deadlock.
Use a conference …
> ENGDESK-17208: Fix deadlock in conference relate api

- conf/vanilla/autoload_configs/amrwb.conf.xml
- src/mod/codecs/mod_amrwb/mod_amrwb.c
- src/switch_core_media.c
Param `silence-supp-off `can be set in mod_amrwb XML config.
If it is on (true) then it turns off silence suppression (CNG)
by appending
`silenceSupp:off - - - -`
to SDP.
> ENGDESK-17768 Add silence-supp-off XML setting

- src/switch_core_media.c
- Prefer rtp_use_ms_per_packet instead of rtp_genesys_dtmf
> TEL-5187: Mark rtp_genesys_dtmf as deprecated variable

- src/switch_apr.c
- src/switch_rtp.c
Fix Segmentation fault in `switch_socket_sendto()` call by `zrtp_send_rtp_callback()`
Previous fix on the same issue [https://github.com/team-telnyx/freeswitch/pull/132](https://github.com/team-telnyx/freeswitch/pull/132)
> TEL-5512: Fix segfault in switch_socket_sendto()

- src/include/switch_types.h
- src/mod/endpoints/mod_sofia/mod_sofia.c
- src/mod/endpoints/mod_sofia/mod_sofia.h
- src/mod/endpoints/mod_sofia/sofia.c
- src/switch_core_session.c
- src/switch_ivr_originate.c
Added in some configuration to allow changing the SIP response upon such a failure for an inbound SIP initial invite.  Also allowed for overriding this limit for outbound SIP call creation.  I did have to add 1 item to an enum in switch_types.h , but I don't foresee any long term issue with that.
> TEL-5473: Decided to go with the builtin min-idle-cpu option for simplicity sake.

- src/mod/endpoints/mod_sofia/mod_sofia.h
- src/mod/endpoints/mod_sofia/sofia.c
This fixes the handling of post-call-recovery dialogs that involve session-timers and should also handle any other in-dialog transactions that are triggered automatically by sofia-sip.  All changes are limited to mod_sofia.h and sofia.c.
> TEL-5573: Post-Recovery Session Timer & Other in-dialog xaction fixes

- src/mod/asr_tts/mod_unimrcp/mod_unimrcp.c
Crash occurred as a result of a null pointer `schannel->mutex` passed to the `switch_mutex_lock` method
```
Segmentation fault (thread 140528481740544, pid 2883416)
Stack trace:
0 [__GI___pthread_mutex_lock()] nptl/pthread_mutex_lock.c:67
1 [apr_thread_mutex_lock()] /usr/local/freeswitch/lib/libfreeswitch.so.1:0x541fe9
2 [switch_mutex_lock()] /SRC/freeswitch/src/switch_apr.c:302
3 [speech_channel_set_state()] /SRC/freeswitch/src/mod/asr_tts/mod_unimrcp/mod_unimrcp.c:1600
4 [speech_on_channel_add()] /SRC/freeswitch/src/mod/asr_tts/mod_unimrcp/mod_unimrcp.c:1958
5 [mrcp_application_message_dispatch()] /usr/local/freeswitch/lib/freeswitch/mod/mod_unimrcp.so:0x2f1d3
6 [recog_message_handler()] /SRC/freeswitch/src/mod/asr_tts/mod_unimrcp/mod_unimrcp.c:3650
7 [mrcp_app_sig_response_raise()] …
```
> TEL-5708: Fix SegFault crash in mod_unimrcp

- Jenkinsfile
- meta-dev.yml
- src/mod/applications/mod_av/avformat.c
- src/mod/endpoints/mod_sofia/mod_sofia.c
- src/mod/endpoints/mod_sofia/mod_sofia.h
- src/mod/endpoints/mod_sofia/sofia.c
- src/mod/endpoints/mod_sofia/sofia_glue.c
- src/mod/endpoints/mod_sofia/sofia_reg.c
- src/switch_ivr_async.c
The only way for this to work properly without flooding the logs until the b2bua keels over was to make a couple very small changes to the core.  The problem is that by the time we receive the file name in mod_av, it's already been stripped such that any calls to switch_ivr_stop_record_session() will fail to find the media bug in the channel's private_hash .
> TEL-5477:  Unblocking the rtmp connections upon failure

- src/mod/asr_tts/mod_unimrcp/mod_unimrcp.c
There's a chance this [PR](https://github.com/team-telnyx/freeswitch/pull/216) fixes the issue. However, I've added additional checks in case it doesn't.
```
Stack trace:
0 [recog_channel_load_grammar()] /SRC/freeswitch/src/mod/asr_tts/mod_unimrcp/mod_unimrcp.c:2537
1 [recog_asr_load_grammar()] /SRC/freeswitch/src/mod/asr_tts/mod_unimrcp/mod_unimrcp.c:3407
2 [switch_core_asr_load_grammar()] /SRC/freeswitch/src/switch_core_asr.c:156
3 [switch_ivr_detect_speech()] /SRC/freeswitch/src/switch_ivr_async.c:5589
...
```
```
Stack trace:
0 [__GI___pthread_mutex_lock()] nptl/pthread_mutex_lock.c:67
1 [apr_thread_mutex_lock()] /usr/local/freeswitch/lib/libfreeswitch.so.1:0x542869
2 [switch_mutex_lock()] /SRC/freeswitch/src/switch_apr.c:302
3 [recog_stream_read()] …
```
> TEL-5763: Fix crashes on mod_unimrcp

- src/mod/endpoints/mod_sofia/sofia.c
It is to capture the whole P-AID header value, which in the case of some clients will include the jurisdictional information (JIP), which is being appended in the params to the PAID.
> ENGDESK-14612: Added the setting of the channel variable p_aid_full

- src/include/switch_core_media.h
- src/mod/endpoints/mod_sofia/sofia.c
- src/switch_core_media.c
- src/switch_rtp.c
- Expose ability to terminate call with SRTP issue
> TEL-5828: Properly log SRTP decryption errors

- src/switch_core_media.c
- src/switch_rtp.c
Patch fixes
- Crypto key received with no MKI index but LIFETIME value
- FS encryption for newly generated crypto key with MKI due to reINVITE
> ENGDESK-28183: Process crypto key with no MKI index

- src/switch_core_media.c
MSteams doesn't honor new key generated due to missing MKI in selected keys.
This patch allows FS to retain local key when only MKI index is missing or not added to the remote key.
> ENGDESK-28234: Skip rebuilding local key for missing MKI

- src/switch_core_media.c
- A possible race condition when receiving RTP text frame and deactivation of RTP text
> TEL-5838: Fix crash when processing text frame

- src/mod/applications/mod_avmd/mod_avmd.c
- Use store session instead of using session locate
- Fix issue on joining detector thread when its null
> TEL-5945: Handle media bug event DESTROY_DATA when media bug fails

- src/switch_core_media.c
Channel variable `rtcp_mux` is controlling whether FS will send in the answer `a=rtcp_mux` or not.
However it is not taken into account when activating the remote RTCP port. If `rtcp-mux` was offered by the remote side, FS will honor it despite not sending `a=rtcp-mux` in the response.
This breaks [RFC 5761 section 5.1.3 ](https://datatracker.ietf.org/doc/html/rfc5761#section-5.1.3).
If FS doesn't send `a=rtcp_mux` in the answer, it has to use the port defined in the offer in `a=rtcp:` as indicated in the RFC.
> ENGDESK-27769: don't use remote rtcp-mux if channel variable rtcp_mux is false

- src/switch_rtp.c
Reduce log by changing them to debug log, on production we disable debug log by default, so change these log to debug level, meaning we disable them on production; and we can enable them we need.
> TEL-6011: Reduce b2bua log usage on graylog

- src/switch_ivr_originate.c
This resolves the bad audio experienced (esp. for G722 codec) when `bridge_early_media` is set and the codec is updated during early media.
Tested this when `inherit_codec` is set and unset. Works fine for both cases.
> TEL-6190: Sync sample rate mismatch for bridge_early_media

- src/switch_rtp.c
This fixes the crash we had yesterday; it will make sure than only complete and supported XR reports will be handled.
> TEL-6127 Do not count in invalid or unsupported XR reports.

- src/mod/codecs/mod_opus/mod_opus.c
this will also fix the upstream [bug](https://github.com/signalwire/freeswitch/issues/2503)
> TEL-6150 Fix opus offering stereo sound when mono is configured.

- src/switch_ivr_play_say.c
I think the issue here was an attempt at creating a stereo L16 codec used for ASR which (IMO) doesn't make sense
> ENGDESK-30126 Fix issue where a potential stereo L16 codec was used in ASR

- src/include/switch_caller.h
- src/include/switch_channel.h
- src/include/switch_types.h
- src/switch_caller.c
- src/switch_channel.c
- src/switch_core_state_machine.c
- tests/unit/Makefile.am
- tests/unit/conf_telnyx/freeswitch.xml
- tests/unit/switch_mod_telnyx.c
@dev-ryanc this is a WIP, but please take a look. thanks
> TEL-6201 Add new functions for setting and getting dialplan function.

- src/switch_rtp.c
B2BUA needs to act as a DTLS server when the other side reports ICE-LITE Fix the bug that was preventing this to happen
> ENGDESK-37949: Initialize DTLS connection for ICE-LITE

- src/include/switch_types.h
- src/mod/applications/mod_dptools/mod_dptools.c
- src/switch_core_media_bug.c
- src/switch_ivr_async.c
- Added parameter for setting position for record_session/uuid_record
- Added parameter for setting position for eavesdrop
- Added parameter for setting position for three_way
- Update parameter for setting position for displace
> ENGDESK-37297: Support for setting position in media bug list
